<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropbtn</name>
   <tag></tag>
   <elementGuidId>fb642dc2-eaa6-4f7e-a07e-069cd99d665e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>dropbtn</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
